apiVersion: v1
kind: Namespace
metadata:
  name: selenosis
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  namespace: selenosis
  name: selenosis
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: selenosis
  namespace: selenosis
roleRef:
  kind: Role
  name: selenosis
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  namespace: selenosis
  name: selenosis
